name: gpg-merger
version: '0.1'
summary:'GPG File Merger is the perfect software to merge mutliple gpg files in one singular gpg file'
description: |
 GPG File Merger is the perfect software to merge mutliple gpg files in one singular gpg file. All separations and formatting is doing under the hook for you.
base: core18
confinement: classic
grade: stable

apps:
  gpg-merger:
    plugs:
    - browser-support
    - gpg-keys
    - gpg-public-keys
    - desktop
    - personal-files
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to ensure
      # libappindicator has readable resources.
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  electron-quick-start:
    plugin: nil
    source: app/
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4